name: Extract hash

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to check and update the engines version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
    
      - name: Extract Engine Commit hash from version
        id: extract-engine-commit-hash
        uses: actions/github-script@v6
        with:
          script: |
            const hash = ${{ github.event.inputs.version }}.split('.').pop()
            core.setOutput('hash', hash)
      - run: echo "${{steps.extract-engine-commit-hash.outputs.hash}}"
